// ===========================================================================
//  WEB WEAVER
//  SIT102 Introduction to Programming - Custom Project (D4 Implementation)
//
//  Dwayne Dias  |  Student ID: s226612714
//
//  An arcade game in which a spider defends a web. The web is not a
//  background image: it is a graph of 32 anchor nodes joined by 48 strands,
//  held in plain arrays and indexed by int. Insects that hit a strand are
//  held there and load it; a strand pushed past its integrity snaps, and a
//  breadth-first search from the anchor nodes decides which parts of the
//  web are still attached. Severed sections go slack, catch nothing, and
//  are drawn greyed out until the player spends a repair charge on them.
//
//  Build:  skm g++ web_weaver.cpp -o web_weaver
//  Run:    ./web_weaver
//
//  Controls
//    Arrow keys   move the spider
//    R            repair the nearest broken strand
//    D            toggle the diagnostic counters
//    G            toggle the collision grid (requires D)
//    P            pause
//    ESC          quit
//
//  SUBMISSION BUILD. This file is generated by make_single.py from the six
//  module pairs in src/ (game_types.h, web, insects, collision, render,
//  main), concatenated in dependency order. Do not edit it directly.
// ===========================================================================

#include "splashkit.h"
#include <cmath>


// -------------------------------------------------------------------------
// SHARED TYPES, ENUMS AND CONSTANTS
// -------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Window and world limits.
// Fixed-size arrays are used throughout in place of dynamic containers, so
// every collection needs a compile-time maximum.
// ---------------------------------------------------------------------------
#define SCREEN_WIDTH        1024
#define SCREEN_HEIGHT       768

#define MAX_INSECTS         64
#define MAX_NODES           64
#define MAX_STRANDS         128
#define MAX_EDGES_PER_NODE  8
#define MAX_SCORES          8
#define LEVEL_COUNT         5

// Broad-phase collision grid. Cell size is derived from these.
#define GRID_COLS           16
#define GRID_ROWS           12
#define MAX_PER_CELL        24

// Web layout.
#define WEB_SPOKES          8
#define WEB_RINGS           3

#define NAME_LENGTH         3

/**
 * The kinds of insect that can spawn. The kind drives point value, size,
 * speed and which steering behaviours are blended, so behaviour is selected
 * by a switch on this value rather than by scattered conditionals.
 */
enum insect_kind
{
    FLY,
    BUTTERFLY,
    WASP,
    GOLDEN
};

/**
 * The screen the game is currently showing. The event loop switches on this
 * to choose which update and draw procedure to run.
 */
enum game_screen
{
    MENU,
    PLAYING,
    PAUSED,
    LEVEL_COMPLETE,
    GAME_OVER,
    SCORES
};

/**
 * The shape a collider represents. A single collision routine reads this to
 * decide which geometric test to perform.
 */
enum shape_kind
{
    SHAPE_CIRCLE,
    SHAPE_SEGMENT
};

/**
 * A drawable, collidable thing with a position and a size.
 * Retained from the Fly Catch worked example.
 */
struct entity
{
    point_2d    pos;
    double      radius;
    color       clr;
    bool        enabled;
};

/**
 * An insect in play. Composes an entity and adds the movement state needed
 * for steering: a current velocity and the force accumulated this frame.
 */
struct insect
{
    entity      ent;
    vector_2d   velocity;
    vector_2d   force;
    insect_kind kind;
    bool        stuck;
    double      stuck_timer;
    int         stuck_strand;   // index of the strand holding it, or -1
    double      wander_angle;   // degrees, carried between frames
    double      life_timer;     // seconds remaining before it leaves
};

/**
 * The spider the player controls. Moves freely across the play area.
 */
struct spider
{
    entity      ent;
    double      speed;
};

/**
 * A junction in the web. Holds the indices of the strands attached to it,
 * which is what makes the node and strand arrays an adjacency structure.
 */
struct web_node
{
    point_2d    pos;
    int         edges[MAX_EDGES_PER_NODE];
    int         edge_count;
    bool        is_anchor;      // fixed to the screen edge
    bool        reachable;      // result of the connectivity search
};

/**
 * A strand of web between two nodes, referenced by node index rather than
 * by pointer. Breaks when tension passes integrity.
 */
struct web_strand
{
    int         node_a;
    int         node_b;
    double      tension;
    double      integrity;
    bool        active;
};

/**
 * The web as a graph: nodes that reference strands, strands that reference
 * nodes, both held in plain arrays indexed by int.
 */
struct web_graph
{
    web_node    nodes[MAX_NODES];
    int         node_count;
    web_strand  strands[MAX_STRANDS];
    int         strand_count;
};

/**
 * A shape to be tested for overlap. Carrying the shape kind alongside the
 * geometry lets one routine resolve every pairing.
 */
struct collider
{
    shape_kind  kind;
    point_2d    a;          // circle centre, or first endpoint of a segment
    point_2d    b;          // second endpoint of a segment (unused for circles)
    double      radius;     // circle radius (unused for segments)
};

/**
 * One cell of the broad-phase grid. Holds the indices of the insects and
 * strands that currently occupy it.
 */
struct grid_cell
{
    int         insects[MAX_PER_CELL];
    int         insect_count;
    int         strands[MAX_PER_CELL];
    int         strand_count;
};

/**
 * Difficulty settings for one level, read from a table rather than being
 * hard-coded into the spawn routine.
 */
struct level
{
    int         target_score;
    double      spawn_interval;
    int         insect_cap;
    double      speed_mult;
};

/**
 * One row of the high score table.
 */
struct score_entry
{
    string      name;
    int         value;
};

/**
 * Everything the game owns. Passing this by reference keeps parameter lists
 * short and lets procedures modify state in place.
 */
struct game_data
{
    spider      player;

    insect      insects[MAX_INSECTS];
    int         insect_count;

    web_graph   web;
    grid_cell   grid[GRID_COLS][GRID_ROWS];

    level       levels[LEVEL_COUNT];
    int         level_index;

    score_entry scores[MAX_SCORES];
    int         score_count;

    int         score;
    int         lives;
    int         repairs;
    double      repair_timer;   // counts up to the next free repair charge
    game_screen screen;

    double      spawn_timer;
    double      elapsed;

    int         comparisons;        // overlap tests actually performed
    int         naive_comparisons;  // tests an all-pairs approach would need
    bool        show_debug;
    bool        show_grid;

    string      entry_name;         // initials being typed at game over
};

// -------------------------------------------------------------------------
// FORWARD DECLARATIONS
// -------------------------------------------------------------------------

void   build_web(web_graph &web);
int    add_strand(web_graph &web, int node_a, int node_b, double integrity);
void   remove_strand(web_graph &web, int strand_id);
void   rebuild_reachability(web_graph &web);
line   strand_line(const web_graph &web, int strand_id);
bool   strand_is_live(const web_graph &web, int strand_id);
int    active_strand_count(const web_graph &web);
int    severed_node_count(const web_graph &web);
void   update_web(game_data &game, double dt);
bool   repair_nearest(game_data &game);


int     insect_value(insect_kind kind);
double  insect_radius(insect_kind kind);
double  insect_max_speed(insect_kind kind);
color   insect_colour(insect_kind kind);
string  insect_name(insect_kind kind);

void    spawn_insect(game_data &game);
void    steer_insect(insect &bug, const game_data &game);
void    update_insects(game_data &game, double dt);
void    remove_insect(game_data &game, int index);
insect *nearest_insect(game_data &game, double within);


collider circle_collider(const point_2d &centre, double radius);
collider segment_collider(const point_2d &a, const point_2d &b);
bool     overlaps(const collider &a, const collider &b);

void     cell_for_point(const point_2d &p, int &col, int &row);
void     build_grid(game_data &game);
void     broad_phase(game_data &game);


void draw_web(const game_data &game);
void draw_insects(const game_data &game);
void draw_spider(const game_data &game);
void draw_hud(const game_data &game);
void draw_debug(const game_data &game);

void draw_menu(const game_data &game);
void draw_playing(const game_data &game);
void draw_paused(const game_data &game);
void draw_level_complete(const game_data &game);
void draw_game_over(const game_data &game);
void draw_scores(const game_data &game);

// -------------------------------------------------------------------------
// WEB GRAPH: construction, breaking, repair, connectivity search
// -------------------------------------------------------------------------

#include <cmath>

/**
 * Attach a strand index to a node's edge list.
 * @param node the node to attach to
 * @param strand_id the index of the strand in the graph's strand array
 */
static void attach_edge(web_node &node, int strand_id)
{
    if (node.edge_count < MAX_EDGES_PER_NODE)
    {
        node.edges[node.edge_count] = strand_id;
        node.edge_count++;
    }
}

/**
 * Remove a strand index from a node's edge list by copying the last entry
 * over it and decrementing the count. Order within an edge list carries no
 * meaning, so compaction is safe here.
 * @param node the node to detach from
 * @param strand_id the strand index to remove
 */
static void detach_edge(web_node &node, int strand_id)
{
    for (int i = 0; i < node.edge_count; i++)
    {
        if (node.edges[i] == strand_id)
        {
            node.edges[i] = node.edges[node.edge_count - 1];
            node.edge_count--;
            return;
        }
    }
}

/**
 * Add a strand between two nodes and register it with both endpoints.
 * @returns the new strand's index, or -1 if the graph is full
 */
int add_strand(web_graph &web, int node_a, int node_b, double integrity)
{
    if (web.strand_count >= MAX_STRANDS) return -1;

    int id = web.strand_count;
    web.strands[id].node_a    = node_a;
    web.strands[id].node_b    = node_b;
    web.strands[id].tension   = 0.0;
    web.strands[id].integrity = integrity;
    web.strands[id].active    = true;
    web.strand_count++;

    attach_edge(web.nodes[node_a], id);
    attach_edge(web.nodes[node_b], id);
    return id;
}

/**
 * Deactivate a strand and detach it from both endpoint nodes. The strand
 * keeps its slot so that indices held elsewhere stay valid; only the active
 * flag and the edge lists change.
 */
void remove_strand(web_graph &web, int strand_id)
{
    if (strand_id < 0 || strand_id >= web.strand_count) return;
    if (not web.strands[strand_id].active) return;

    web.strands[strand_id].active  = false;
    web.strands[strand_id].tension = 0.0;
    detach_edge(web.nodes[web.strands[strand_id].node_a], strand_id);
    detach_edge(web.nodes[web.strands[strand_id].node_b], strand_id);
}

/**
 * Build the starting web: a radial structure of concentric rings joined by
 * spokes, with anchor nodes fixed near the screen corners.
 */
void build_web(web_graph &web)
{
    web.node_count   = 0;
    web.strand_count = 0;

    double cx = SCREEN_WIDTH / 2.0;
    // Centred between the HUD bar and the bottom edge, sized so the anchor
    // ring stays fully on screen.
    double cy = 406.0;
    double ring_radius[WEB_RINGS] = { 90.0, 160.0, 225.0 };

    // Ring and spoke nodes. Index = ring * WEB_SPOKES + spoke.
    for (int ring = 0; ring < WEB_RINGS; ring++)
    {
        for (int spoke = 0; spoke < WEB_SPOKES; spoke++)
        {
            double angle = spoke * (360.0 / WEB_SPOKES) * M_PI / 180.0;
            int id = web.node_count;
            web.nodes[id].pos        = point_at(cx + cos(angle) * ring_radius[ring],
                                                cy + sin(angle) * ring_radius[ring]);
            web.nodes[id].edge_count = 0;
            web.nodes[id].is_anchor  = false;
            web.nodes[id].reachable  = true;
            web.node_count++;
        }
    }

    // Eight anchor nodes out towards the screen edge. More anchors means a
    // single failure cannot detach the whole web.
    int first_anchor = web.node_count;
    double anchor_radius = 330.0;
    for (int i = 0; i < WEB_SPOKES; i++)
    {
        double angle = (i * (360.0 / WEB_SPOKES)) * M_PI / 180.0;
        int id = web.node_count;
        web.nodes[id].pos        = point_at(cx + cos(angle) * anchor_radius,
                                            cy + sin(angle) * anchor_radius);
        web.nodes[id].edge_count = 0;
        web.nodes[id].is_anchor  = true;
        web.nodes[id].reachable  = true;
        web.node_count++;
    }

    // Circumferential strands around each ring.
    for (int ring = 0; ring < WEB_RINGS; ring++)
    {
        for (int spoke = 0; spoke < WEB_SPOKES; spoke++)
        {
            int a = ring * WEB_SPOKES + spoke;
            int b = ring * WEB_SPOKES + ((spoke + 1) % WEB_SPOKES);
            add_strand(web, a, b, 100.0 + ring * 20.0);
        }
    }

    // Radial strands joining each ring to the next.
    for (int ring = 0; ring < WEB_RINGS - 1; ring++)
    {
        for (int spoke = 0; spoke < WEB_SPOKES; spoke++)
        {
            int a = ring * WEB_SPOKES + spoke;
            int b = (ring + 1) * WEB_SPOKES + spoke;
            add_strand(web, a, b, 120.0);
        }
    }

    // Anchor strands from the outer ring to the anchors. These are the
    // structural strands, so they are the strongest in the web.
    for (int i = 0; i < WEB_SPOKES; i++)
    {
        int outer = (WEB_RINGS - 1) * WEB_SPOKES + i;
        add_strand(web, outer, first_anchor + i, 300.0);
    }

    rebuild_reachability(web);
}

/**
 * Recalculate which nodes are still connected to an anchor, using a
 * breadth-first search outward from every anchor node.
 *
 * The search has to be re-run whenever a strand is added or removed,
 * because connectivity cannot be worked out in advance once the graph
 * changes during play.
 */
void rebuild_reachability(web_graph &web)
{
    int queue[MAX_NODES];
    int head = 0;
    int tail = 0;

    // 1. Clear the reachable flag on every node.
    for (int i = 0; i < web.node_count; i++)
    {
        web.nodes[i].reachable = false;
    }

    // 2. Push every anchor node and mark it reachable.
    for (int i = 0; i < web.node_count; i++)
    {
        if (web.nodes[i].is_anchor)
        {
            web.nodes[i].reachable = true;
            queue[tail] = i;
            tail++;
        }
    }

    // 3. Pop a node, walk its edge list, and push any endpoint not yet seen.
    while (head < tail)
    {
        int current = queue[head];
        head++;

        for (int e = 0; e < web.nodes[current].edge_count; e++)
        {
            int strand_id = web.nodes[current].edges[e];
            if (not web.strands[strand_id].active) continue;

            // The node at the other end of this strand.
            int other = web.strands[strand_id].node_a;
            if (other == current) other = web.strands[strand_id].node_b;

            if (not web.nodes[other].reachable)
            {
                web.nodes[other].reachable = true;
                queue[tail] = other;
                tail++;
            }
        }
    }

    // 4. Any node still unmarked is severed from every anchor.
}

/**
 * @returns the strand as a line between its two endpoint node positions
 */
line strand_line(const web_graph &web, int strand_id)
{
    return line_from(web.nodes[web.strands[strand_id].node_a].pos,
                     web.nodes[web.strands[strand_id].node_b].pos);
}

/**
 * A strand is live when it is active and both of its endpoints are still
 * connected to an anchor. Slack strands are drawn greyed out and catch
 * nothing.
 */
bool strand_is_live(const web_graph &web, int strand_id)
{
    if (not web.strands[strand_id].active) return false;
    return web.nodes[web.strands[strand_id].node_a].reachable
        and web.nodes[web.strands[strand_id].node_b].reachable;
}

/**
 * @returns how many strands are currently active
 */
int active_strand_count(const web_graph &web)
{
    int count = 0;
    for (int i = 0; i < web.strand_count; i++)
    {
        if (web.strands[i].active) count++;
    }
    return count;
}

/**
 * @returns how many non-anchor nodes have been cut off from every anchor
 */
int severed_node_count(const web_graph &web)
{
    int count = 0;
    for (int i = 0; i < web.node_count; i++)
    {
        if (not web.nodes[i].reachable) count++;
    }
    return count;
}

/**
 * Advance strand tension. Tension bleeds away on its own, and any strand
 * pushed past its integrity snaps, which triggers a fresh connectivity
 * search because the shape of the graph has changed.
 */
void update_web(game_data &game, double dt)
{
    bool graph_changed = false;

    for (int i = 0; i < game.web.strand_count; i++)
    {
        if (not game.web.strands[i].active) continue;

        game.web.strands[i].tension -= 14.0 * dt;
        if (game.web.strands[i].tension < 0.0)
        {
            game.web.strands[i].tension = 0.0;
        }

        if (game.web.strands[i].tension >= game.web.strands[i].integrity)
        {
            remove_strand(game.web, i);
            graph_changed = true;
        }
    }

    if (graph_changed)
    {
        rebuild_reachability(game.web);
    }
}

/**
 * Spend a repair charge to restore the broken strand nearest the spider.
 * Restoring an edge changes the graph, so reachability is recalculated.
 * @returns true if a strand was repaired
 */
bool repair_nearest(game_data &game)
{
    if (game.repairs <= 0) return false;

    int    best     = -1;
    double best_gap = 220.0;   // spider must be reasonably close

    for (int i = 0; i < game.web.strand_count; i++)
    {
        if (game.web.strands[i].active) continue;

        point_2d a = game.web.nodes[game.web.strands[i].node_a].pos;
        point_2d b = game.web.nodes[game.web.strands[i].node_b].pos;
        point_2d mid = point_at((a.x + b.x) / 2.0, (a.y + b.y) / 2.0);

        double gap = point_point_distance(game.player.ent.pos, mid);
        if (gap < best_gap)
        {
            best_gap = gap;
            best     = i;
        }
    }

    if (best < 0) return false;

    game.web.strands[best].active  = true;
    game.web.strands[best].tension = 0.0;
    attach_edge(game.web.nodes[game.web.strands[best].node_a], best);
    attach_edge(game.web.nodes[game.web.strands[best].node_b], best);
    game.repairs--;

    rebuild_reachability(game.web);
    return true;
}

// -------------------------------------------------------------------------
// INSECTS: steering behaviours, spawning, array lifecycle
// -------------------------------------------------------------------------

#include <cmath>

#define MAX_STEER_FORCE 220.0

/** @returns the points awarded for catching this kind of insect */
int insect_value(insect_kind kind)
{
    switch (kind)
    {
        case FLY:       return 10;
        case BUTTERFLY: return 25;
        case WASP:      return 40;
        case GOLDEN:    return 100;
    }
    return 0;
}

/** @returns the drawn and collidable radius for this kind of insect */
double insect_radius(insect_kind kind)
{
    switch (kind)
    {
        case FLY:       return 9.0;
        case BUTTERFLY: return 12.0;
        case WASP:      return 12.0;
        case GOLDEN:    return 10.0;
    }
    return 9.0;
}

/** @returns the speed ceiling applied after the steering force is added */
double insect_max_speed(insect_kind kind)
{
    switch (kind)
    {
        case FLY:       return 105.0;
        case BUTTERFLY: return 85.0;
        case WASP:      return 130.0;
        case GOLDEN:    return 150.0;
    }
    return 100.0;
}

/** @returns the colour used to draw this kind of insect */
color insect_colour(insect_kind kind)
{
    switch (kind)
    {
        case FLY:       return rgba_color(95, 143, 74, 255);
        case BUTTERFLY: return rgba_color(237, 147, 177, 255);
        case WASP:      return rgba_color(239, 159, 39, 255);
        case GOLDEN:    return rgba_color(242, 193, 74, 255);
    }
    return color_white();
}

/** @returns a readable name for this kind, used by the debug overlay */
string insect_name(insect_kind kind)
{
    switch (kind)
    {
        case FLY:       return "Fly";
        case BUTTERFLY: return "Butterfly";
        case WASP:      return "Wasp";
        case GOLDEN:    return "Golden";
    }
    return "Unknown";
}

/**
 * A steering force that pulls towards a point.
 * @param from where the insect is now
 * @param target where it wants to be
 * @param strength the magnitude of the returned force
 */
static vector_2d seek(const point_2d &from, const point_2d &target, double strength)
{
    vector_2d desired = vector_point_to_point(from, target);
    if (vector_magnitude(desired) < 0.0001) return vector_to(0, 0);
    return vector_multiply(unit_vector(desired), strength);
}

/**
 * A steering force that pushes directly away from a point.
 */
static vector_2d flee(const point_2d &from, const point_2d &threat, double strength)
{
    return vector_multiply(seek(from, threat, strength), -1.0);
}

/**
 * A steering force that drifts, turning by a small random amount each frame.
 * The angle is stored on the insect so the drift is continuous rather than
 * re-randomised every frame, which would just produce jitter.
 */
static vector_2d wander(insect &bug, double strength, double turn_rate)
{
    bug.wander_angle += (rnd() - 0.5) * turn_rate;
    return vector_from_angle(bug.wander_angle, strength);
}

/**
 * Blend the steering behaviours for this insect's kind into a single force.
 * The switch decides which behaviours contribute and with what weighting, so
 * a movement pattern is a combination of forces rather than a special case.
 */
void steer_insect(insect &bug, const game_data &game)
{
    bug.force = vector_to(0, 0);

    switch (bug.kind)
    {
        case FLY:
            // Drifts aimlessly, with a mild pull away from the spider.
            bug.force = vector_add(bug.force, wander(bug, 150.0, 55.0));
            bug.force = vector_add(bug.force, flee(bug.ent.pos, game.player.ent.pos, 45.0));
            break;

        case BUTTERFLY:
        {
            // Wanders slowly, with a sideways oscillation that produces the
            // characteristic fluttering path.
            bug.force = vector_add(bug.force, wander(bug, 90.0, 25.0));

            // vector_normal is undefined for a zero-length vector, which a
            // butterfly has on the frame it is released from a strand.
            if (vector_magnitude(bug.velocity) > 0.0001)
            {
                vector_2d side = vector_normal(bug.velocity);
                double sway = sin(game.elapsed * 6.0 + bug.wander_angle) * 130.0;
                bug.force = vector_add(bug.force, vector_multiply(side, sway));
            }
            break;
        }

        case WASP:
            // Hunts the spider directly.
            bug.force = vector_add(bug.force, seek(bug.ent.pos, game.player.ent.pos, 190.0));
            bug.force = vector_add(bug.force, wander(bug, 40.0, 30.0));
            break;

        case GOLDEN:
            // Fast, erratic, and actively avoids the spider.
            bug.force = vector_add(bug.force, wander(bug, 200.0, 90.0));
            bug.force = vector_add(bug.force, flee(bug.ent.pos, game.player.ent.pos, 150.0));
            break;
    }

    // Clamp the force before it reaches the velocity. Without this an insect
    // blending several strong behaviours accelerates far harder than one
    // blending a single behaviour.
    bug.force = vector_limit(bug.force, MAX_STEER_FORCE);
}

/**
 * Add an insect at a random point just outside the screen edge, aimed
 * roughly inward. Kind is weighted so flies are common and golden flies rare.
 */
void spawn_insect(game_data &game)
{
    if (game.insect_count >= MAX_INSECTS) return;
    if (game.insect_count >= game.levels[game.level_index].insect_cap) return;

    insect bug;

    // Wasp share is reduced to offset the higher spawn rate, so overall
    // density rises while the number of wasps per second stays the same.
    int roll = rnd(100);
    if      (roll < 46) bug.kind = FLY;        // 46%
    else if (roll < 74) bug.kind = BUTTERFLY;  // 28%
    else if (roll < 85) bug.kind = WASP;       // 11%
    else                bug.kind = GOLDEN;     // 15%

    // Choose an edge, then a position along it.
    int edge = rnd(4);
    double x = 0, y = 0;
    switch (edge)
    {
        case 0: x = rnd(SCREEN_WIDTH); y = -20;                 break;
        case 1: x = rnd(SCREEN_WIDTH); y = SCREEN_HEIGHT + 20;  break;
        case 2: x = -20;               y = rnd(SCREEN_HEIGHT);  break;
        case 3: x = SCREEN_WIDTH + 20; y = rnd(SCREEN_HEIGHT);  break;
    }

    bug.ent.pos      = point_at(x, y);
    bug.ent.radius   = insect_radius(bug.kind);
    bug.ent.clr      = insect_colour(bug.kind);
    bug.ent.enabled  = true;
    bug.velocity     = seek(bug.ent.pos, point_at(SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0), 60.0);
    bug.force        = vector_to(0, 0);
    bug.stuck        = false;
    bug.stuck_timer  = 0.0;
    bug.stuck_strand = -1;
    bug.wander_angle = rnd(360);
    bug.life_timer   = 9.0 + rnd(6);

    game.insects[game.insect_count] = bug;
    game.insect_count++;
}

/**
 * Remove an insect by copying the last active element over it and
 * decrementing the count. Order in the array carries no meaning, so this
 * avoids shuffling every later element down.
 */
void remove_insect(game_data &game, int index)
{
    if (index < 0 || index >= game.insect_count) return;
    game.insects[index] = game.insects[game.insect_count - 1];
    game.insect_count--;
}

/**
 * Find the insect closest to the spider within a given range.
 * @returns a pointer to that insect, or nullptr when nothing is in range
 */
insect *nearest_insect(game_data &game, double within)
{
    insect *found    = nullptr;
    double  best_gap = within;

    for (int i = 0; i < game.insect_count; i++)
    {
        double gap = point_point_distance(game.player.ent.pos, game.insects[i].ent.pos);
        if (gap < best_gap)
        {
            best_gap = gap;
            found    = &game.insects[i];
        }
    }
    return found;
}

/**
 * Advance every insect: steer, integrate, clamp, and expire.
 * Stuck insects do not move, but they do load the strand holding them.
 */
void update_insects(game_data &game, double dt)
{
    double speed_mult = game.levels[game.level_index].speed_mult;

    for (int i = 0; i < game.insect_count; i++)
    {
        insect &bug = game.insects[i];

        if (bug.stuck)
        {
            bug.stuck_timer -= dt;

            // A held insect keeps loading the strand it is caught on.
            if (bug.stuck_strand >= 0 and game.web.strands[bug.stuck_strand].active)
            {
                game.web.strands[bug.stuck_strand].tension += 16.0 * dt;
            }
            else
            {
                bug.stuck = false;   // the strand broke underneath it
            }

            if (bug.stuck_timer <= 0.0)
            {
                bug.stuck        = false;
                bug.stuck_strand = -1;
            }
            continue;
        }

        steer_insect(bug, game);

        // Integrate the force into the velocity, then clamp the velocity.
        // Clamping at both stages is what keeps movement smooth: limiting
        // only the force still lets speed accumulate without bound.
        bug.velocity = vector_add(bug.velocity, vector_multiply(bug.force, dt));
        bug.velocity = vector_limit(bug.velocity, insect_max_speed(bug.kind) * speed_mult);

        bug.ent.pos.x += bug.velocity.x * dt;
        bug.ent.pos.y += bug.velocity.y * dt;

        // Keep insects loosely within the play area.
        if (bug.ent.pos.x < -40)                bug.ent.pos.x = -40;
        if (bug.ent.pos.x > SCREEN_WIDTH + 40)  bug.ent.pos.x = SCREEN_WIDTH + 40;
        if (bug.ent.pos.y < -40)                bug.ent.pos.y = -40;
        if (bug.ent.pos.y > SCREEN_HEIGHT + 40) bug.ent.pos.y = SCREEN_HEIGHT + 40;

        bug.life_timer -= dt;
        if (bug.life_timer <= 0.0)
        {
            remove_insect(game, i);
            i--;   // the element now at i has not been processed yet
        }
    }
}

// -------------------------------------------------------------------------
// COLLISION: unified narrow phase, spatial grid broad phase
// -------------------------------------------------------------------------

#include <cmath>

#define CELL_WIDTH  (SCREEN_WIDTH  / (double)GRID_COLS)
#define CELL_HEIGHT (SCREEN_HEIGHT / (double)GRID_ROWS)
#define STICK_TIME  2.0

/** Build a circular collider. */
collider circle_collider(const point_2d &centre, double radius)
{
    collider c;
    c.kind   = SHAPE_CIRCLE;
    c.a      = centre;
    c.b      = centre;
    c.radius = radius;
    return c;
}

/** Build a line-segment collider between two points. */
collider segment_collider(const point_2d &a, const point_2d &b)
{
    collider c;
    c.kind   = SHAPE_SEGMENT;
    c.a      = a;
    c.b      = b;
    c.radius = 0.0;
    return c;
}

/**
 * Test two colliders for overlap. One routine resolves every pairing by
 * reading the shape kind, so adding a shape means extending this function
 * rather than adding a parallel collision path elsewhere.
 */
bool overlaps(const collider &a, const collider &b)
{
    if (a.kind == SHAPE_CIRCLE and b.kind == SHAPE_CIRCLE)
    {
        return point_point_distance(a.a, b.a) <= a.radius + b.radius;
    }

    // Circle against segment, in whichever order the pair arrived.
    const collider &circle  = (a.kind == SHAPE_CIRCLE) ? a : b;
    const collider &segment = (a.kind == SHAPE_CIRCLE) ? b : a;

    if (circle.kind == segment.kind) return false;   // segment against segment

    return point_line_distance(circle.a, line_from(segment.a, segment.b)) <= circle.radius;
}

/**
 * Work out which grid cell a point falls in, clamped to the grid bounds so
 * that entities just off screen still land in a valid cell.
 */
void cell_for_point(const point_2d &p, int &col, int &row)
{
    col = (int)(p.x / CELL_WIDTH);
    row = (int)(p.y / CELL_HEIGHT);

    if (col < 0) col = 0;
    if (row < 0) row = 0;
    if (col >= GRID_COLS) col = GRID_COLS - 1;
    if (row >= GRID_ROWS) row = GRID_ROWS - 1;
}

/** Add an insect index to a cell, ignoring it if the cell is full. */
static void add_insect_to_cell(grid_cell &cell, int index)
{
    if (cell.insect_count < MAX_PER_CELL)
    {
        cell.insects[cell.insect_count] = index;
        cell.insect_count++;
    }
}

/** Add a strand index to a cell unless it is already listed there. */
static void add_strand_to_cell(grid_cell &cell, int index)
{
    for (int i = 0; i < cell.strand_count; i++)
    {
        if (cell.strands[i] == index) return;
    }
    if (cell.strand_count < MAX_PER_CELL)
    {
        cell.strands[cell.strand_count] = index;
        cell.strand_count++;
    }
}

/**
 * Sort every insect and strand into the grid.
 *
 * Insects occupy a single cell. Strands are line segments that can cross
 * several, so each strand is walked in short steps and registered in every
 * cell it passes through.
 */
void build_grid(game_data &game)
{
    for (int c = 0; c < GRID_COLS; c++)
    {
        for (int r = 0; r < GRID_ROWS; r++)
        {
            game.grid[c][r].insect_count = 0;
            game.grid[c][r].strand_count = 0;
        }
    }

    for (int i = 0; i < game.insect_count; i++)
    {
        int col, row;
        cell_for_point(game.insects[i].ent.pos, col, row);
        add_insect_to_cell(game.grid[col][row], i);
    }

    for (int s = 0; s < game.web.strand_count; s++)
    {
        if (not strand_is_live(game.web, s)) continue;

        point_2d a = game.web.nodes[game.web.strands[s].node_a].pos;
        point_2d b = game.web.nodes[game.web.strands[s].node_b].pos;

        double span  = point_point_distance(a, b);
        int    steps = (int)(span / (CELL_WIDTH / 2.0)) + 1;

        for (int step = 0; step <= steps; step++)
        {
            double t = (double)step / steps;
            point_2d along = point_at(a.x + (b.x - a.x) * t,
                                      a.y + (b.y - a.y) * t);
            int col, row;
            cell_for_point(along, col, row);
            add_strand_to_cell(game.grid[col][row], s);
        }
    }
}

/**
 * Run collision for the frame.
 *
 * Testing every insect against every strand grows with the product of the
 * two counts. The grid exists to avoid those tests: each insect is only
 * tested against the strands registered in its own cell and the eight
 * around it. Two counters record the tests performed and the number an
 * all-pairs approach would have required, so the reduction is measured
 * rather than claimed.
 */
void broad_phase(game_data &game)
{
    game.comparisons = 0;

    // The all-pairs figure must count the same strands the grid can return,
    // otherwise the comparison flatters the grid once parts of the web go
    // slack. Only live strands are ever tested, so only those are counted.
    int live_strands = 0;
    for (int s = 0; s < game.web.strand_count; s++)
    {
        if (strand_is_live(game.web, s)) live_strands++;
    }
    game.naive_comparisons = game.insect_count * live_strands + game.insect_count;

    build_grid(game);

    collider spider_col = circle_collider(game.player.ent.pos, game.player.ent.radius);

    // --- Spider against the insects in its own cell and the eight around it.
    int scol, srow;
    cell_for_point(game.player.ent.pos, scol, srow);

    for (int dc = -1; dc <= 1; dc++)
    {
        for (int dr = -1; dr <= 1; dr++)
        {
            int col = scol + dc;
            int row = srow + dr;
            if (col < 0 or row < 0 or col >= GRID_COLS or row >= GRID_ROWS) continue;

            grid_cell &cell = game.grid[col][row];
            for (int k = 0; k < cell.insect_count; k++)
            {
                int index = cell.insects[k];
                if (index >= game.insect_count) continue;

                insect &bug = game.insects[index];
                collider bug_col = circle_collider(bug.ent.pos, bug.ent.radius);

                game.comparisons++;
                if (not overlaps(spider_col, bug_col)) continue;

                if (bug.kind == WASP and not bug.stuck)
                {
                    // A free wasp hurts. A trapped one can be taken safely.
                    game.lives--;
                    remove_insect(game, index);
                    if (game.lives <= 0) game.screen = GAME_OVER;
                    return;
                }

                game.score += insect_value(bug.kind);
                remove_insect(game, index);
            }
        }
    }

    // --- Insects against the strands registered near them.
    for (int i = 0; i < game.insect_count; i++)
    {
        insect &bug = game.insects[i];
        if (bug.stuck) continue;

        int col, row;
        cell_for_point(bug.ent.pos, col, row);
        collider bug_col = circle_collider(bug.ent.pos, bug.ent.radius);

        grid_cell &cell = game.grid[col][row];
        for (int k = 0; k < cell.strand_count; k++)
        {
            int s = cell.strands[k];
            if (not strand_is_live(game.web, s)) continue;

            collider strand_col = segment_collider(
                game.web.nodes[game.web.strands[s].node_a].pos,
                game.web.nodes[game.web.strands[s].node_b].pos);

            game.comparisons++;
            if (not overlaps(bug_col, strand_col)) continue;

            if (bug.kind == WASP)
            {
                // Wasps cut through rather than sticking.
                game.web.strands[s].tension += 30.0;
            }
            else
            {
                bug.stuck        = true;
                bug.stuck_timer  = STICK_TIME;
                bug.stuck_strand = s;
                bug.velocity     = vector_to(0, 0);
            }
            break;
        }
    }
}

// -------------------------------------------------------------------------
// RENDERING: web, entities, HUD, diagnostic overlay, screens
// -------------------------------------------------------------------------

#define BACKGROUND    rgba_color( 28,  43,  31, 255)
#define HUD_BAR       rgba_color( 19,  29,  22, 255)
#define TEXT_BRIGHT   rgba_color(232, 239, 228, 255)
#define TEXT_DIM      rgba_color(159, 181, 153, 255)
#define STRAND_OK     rgba_color(107, 127,  94, 255)
#define STRAND_WARM   rgba_color(239, 159,  39, 255)
#define STRAND_HOT    rgba_color(226,  75,  74, 255)
#define STRAND_SLACK  rgba_color( 90,  95,  86, 255)
#define NODE_ANCHOR   rgba_color(143, 168, 138, 255)
#define NODE_LIVE     rgba_color( 95, 115,  88, 255)
#define NODE_DEAD     rgba_color( 74,  79,  70, 255)
#define SPIDER_BODY   rgba_color( 43,  28,  21, 255)
#define DEBUG_TEXT    rgba_color(127, 212, 168, 255)

// The default SplashKit font is a fixed-width bitmap font, eight pixels per
// character. There is no text_width for it, so centring is calculated from
// the string length instead.
#define CHAR_WIDTH    8.0

/**
 * Draw text centred horizontally on the screen.
 * @param text the string to draw
 * @param clr its colour
 * @param y the top of the text
 */
static void draw_centred(const string &text, const color &clr, double y)
{
    draw_text(text, clr, SCREEN_WIDTH / 2.0 - (text.length() * CHAR_WIDTH) / 2.0, y);
}

/**
 * Draw a heading centred on the screen.
 */
static void draw_heading(const string &text, const color &clr, double y)
{
    draw_text(text, clr, SCREEN_WIDTH / 2.0 - (text.length() * CHAR_WIDTH) / 2.0, y);
}

/**
 * Pick a strand's colour from its state: slack strands are greyed out, and
 * live strands shift from green through amber to red as tension rises, so
 * the player can see which parts of the web are about to fail.
 */
static color strand_colour(const web_graph &web, int strand_id)
{
    if (not strand_is_live(web, strand_id)) return STRAND_SLACK;

    double load = web.strands[strand_id].tension / web.strands[strand_id].integrity;
    if (load > 0.66) return STRAND_HOT;
    if (load > 0.33) return STRAND_WARM;
    return STRAND_OK;
}

/** Draw every active strand and node. */
void draw_web(const game_data &game)
{
    for (int i = 0; i < game.web.strand_count; i++)
    {
        if (not game.web.strands[i].active) continue;

        point_2d a = game.web.nodes[game.web.strands[i].node_a].pos;
        point_2d b = game.web.nodes[game.web.strands[i].node_b].pos;
        draw_line(strand_colour(game.web, i), a.x, a.y, b.x, b.y);
    }

    for (int i = 0; i < game.web.node_count; i++)
    {
        color node_clr = NODE_DEAD;
        if (game.web.nodes[i].reachable)
        {
            node_clr = game.web.nodes[i].is_anchor ? NODE_ANCHOR : NODE_LIVE;
        }
        double r = game.web.nodes[i].is_anchor ? 6.0 : 4.0;
        fill_circle(node_clr, game.web.nodes[i].pos.x, game.web.nodes[i].pos.y, r);
    }
}

/** Draw every insect, ringing the ones currently held on a strand. */
void draw_insects(const game_data &game)
{
    for (int i = 0; i < game.insect_count; i++)
    {
        const insect &bug = game.insects[i];
        fill_circle(bug.ent.clr, bug.ent.pos.x, bug.ent.pos.y, bug.ent.radius);

        if (bug.kind == WASP)
        {
            // A dark bar makes the dangerous insect readable at a glance.
            fill_rectangle(SPIDER_BODY,
                           bug.ent.pos.x - 2, bug.ent.pos.y - bug.ent.radius,
                           4, bug.ent.radius * 2);
        }

        if (bug.stuck)
        {
            draw_circle(TEXT_BRIGHT, bug.ent.pos.x, bug.ent.pos.y, bug.ent.radius + 5);
        }
    }
}

/** Draw the spider as a body with legs. */
void draw_spider(const game_data &game)
{
    double x = game.player.ent.pos.x;
    double y = game.player.ent.pos.y;
    double r = game.player.ent.radius;

    for (int i = 0; i < 3; i++)
    {
        double offset = (i - 1) * 8.0;
        draw_line(SPIDER_BODY, x - r * 0.5, y + offset, x - r * 1.7, y + offset - 6);
        draw_line(SPIDER_BODY, x + r * 0.5, y + offset, x + r * 1.7, y + offset - 6);
    }

    fill_circle(SPIDER_BODY, x, y, r);
    fill_circle(rgba_color(59, 40, 32, 255), x, y - r * 0.45, r * 0.55);
}

/** Draw the status bar across the top of the play area. */
void draw_hud(const game_data &game)
{
    const level &lv = game.levels[game.level_index];

    fill_rectangle(HUD_BAR, 0, 0, SCREEN_WIDTH, 44);
    draw_text("Score " + to_string(game.score), TEXT_BRIGHT, 16, 16);
    draw_text("Target " + to_string(lv.target_score), TEXT_DIM, 140, 16);
    draw_text("Level " + to_string(game.level_index + 1), TEXT_DIM, 270, 16);
    draw_text("Lives " + to_string(game.lives), TEXT_DIM, 370, 16);
    draw_text("Repairs " + to_string(game.repairs), TEXT_DIM, 470, 16);
    draw_text("R repair  D debug  G grid  P pause", TEXT_DIM, 600, 16);
}

/**
 * Draw the diagnostic counters, and optionally the grid itself.
 *
 * The two comparison figures are the evidence for the broad phase: the
 * first is what the frame actually cost, the second is what testing every
 * insect against every live strand would have cost.
 */
void draw_debug(const game_data &game)
{
    fill_rectangle(rgba_color(13, 22, 16, 220), 12, SCREEN_HEIGHT - 86, 330, 74);

    draw_text("DEBUG", DEBUG_TEXT, 24, SCREEN_HEIGHT - 78);
    draw_text("overlap tests this frame : " + to_string(game.comparisons),
              DEBUG_TEXT, 24, SCREEN_HEIGHT - 60);
    draw_text("all-pairs would have cost : " + to_string(game.naive_comparisons),
              DEBUG_TEXT, 24, SCREEN_HEIGHT - 42);
    draw_text("severed nodes : " + to_string(severed_node_count(game.web))
              + "   strands : " + to_string(active_strand_count(game.web)),
              DEBUG_TEXT, 24, SCREEN_HEIGHT - 24);

    if (not game.show_grid) return;

    color grid_clr = rgba_color(127, 212, 168, 45);
    for (int c = 1; c < GRID_COLS; c++)
    {
        double x = c * (SCREEN_WIDTH / (double)GRID_COLS);
        draw_line(grid_clr, x, 44, x, SCREEN_HEIGHT);
    }
    for (int r = 1; r < GRID_ROWS; r++)
    {
        double y = r * (SCREEN_HEIGHT / (double)GRID_ROWS);
        if (y < 44) continue;
        draw_line(grid_clr, 0, y, SCREEN_WIDTH, y);
    }
}

/** Draw the title screen. */
void draw_menu(const game_data &game)
{
    clear_screen(BACKGROUND);
    draw_web(game);
    draw_heading("WEB WEAVER", TEXT_BRIGHT, 180);
    draw_centred("Catch insects. Keep the web attached to its anchors.", TEXT_DIM, 220);
    draw_centred("ENTER to start      S for high scores      ESC to quit", TEXT_DIM, 250);
}

/** Draw the play screen. */
void draw_playing(const game_data &game)
{
    clear_screen(BACKGROUND);
    draw_web(game);
    draw_insects(game);
    draw_spider(game);
    draw_hud(game);
    if (game.show_debug) draw_debug(game);
}

/** Draw the play screen dimmed, with a pause notice. */
void draw_paused(const game_data &game)
{
    draw_playing(game);
    fill_rectangle(rgba_color(0, 0, 0, 150), 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);
    draw_heading("PAUSED", TEXT_BRIGHT, SCREEN_HEIGHT / 2);
    draw_centred("P to resume", TEXT_DIM, SCREEN_HEIGHT / 2 + 26);
}

/** Draw the between-levels screen. */
void draw_level_complete(const game_data &game)
{
    clear_screen(BACKGROUND);
    draw_web(game);
    draw_heading("LEVEL " + to_string(game.level_index + 1) + " COMPLETE", TEXT_BRIGHT, 250);
    draw_centred("Score " + to_string(game.score), TEXT_DIM, 285);
    draw_centred("ENTER to continue", TEXT_DIM, 315);
}

/** Draw the game over screen, including initials entry when the score qualifies. */
void draw_game_over(const game_data &game)
{
    clear_screen(BACKGROUND);
    draw_web(game);
    draw_heading("GAME OVER", TEXT_BRIGHT, 240);
    draw_centred("Final score " + to_string(game.score), TEXT_DIM, 275);
    draw_heading("Initials: " + game.entry_name + "_", TEXT_BRIGHT, 315);
    draw_centred("Type three letters, then ENTER", TEXT_DIM, 345);
}

/** Draw the ranked high score table. */
void draw_scores(const game_data &game)
{
    clear_screen(BACKGROUND);
    draw_heading("HIGH SCORES", TEXT_BRIGHT, 160);

    if (game.score_count == 0)
    {
        draw_centred("No scores yet.", TEXT_DIM, 210);
    }

    for (int i = 0; i < game.score_count; i++)
    {
        draw_text(to_string(i + 1) + ".", TEXT_DIM, SCREEN_WIDTH / 2 - 110, 210 + i * 26);
        draw_text(game.scores[i].name, TEXT_BRIGHT, SCREEN_WIDTH / 2 - 70, 210 + i * 26);
        draw_text(to_string(game.scores[i].value), TEXT_BRIGHT,
                  SCREEN_WIDTH / 2 + 30, 210 + i * 26);
    }

    draw_centred("ENTER to return", TEXT_DIM, 210 + MAX_SCORES * 26 + 30);
}

// -------------------------------------------------------------------------
// MAIN: level table, screen state machine, event loop
// -------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Web Weaver - SIT102 Custom Project
//
// An arcade game in which a spider defends a web built as a graph of anchor
// nodes joined by strands. Insects that hit a strand are held there and load
// it; overloaded strands snap, and a breadth-first search decides which parts
// of the web are still connected to an anchor. Severed sections go slack and
// catch nothing until they are repaired.
// ---------------------------------------------------------------------------


#define REPAIR_RECHARGE  6.0    // seconds between free repair charges
#define MAX_REPAIRS      8

/**
 * Fill the level table. Difficulty is data read by the spawn routine rather
 * than branches written into it, so tuning the curve means editing values.
 */
static void load_levels(game_data &game)
{
    //                     target  spawn   cap  speed
    game.levels[0] = level{   250,   0.70,  16,  0.85 };
    game.levels[1] = level{   600,   0.58,  22,  1.00 };
    game.levels[2] = level{  1100,   0.48,  28,  1.15 };
    game.levels[3] = level{  1800,   0.40,  34,  1.30 };
    game.levels[4] = level{  2800,   0.33,  42,  1.45 };
}

/**
 * Reset everything needed to begin a run at level one.
 */
static void start_new_game(game_data &game)
{
    build_web(game.web);

    game.player.ent.pos     = point_at(SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0);
    game.player.ent.radius  = 20.0;
    game.player.ent.enabled = true;
    game.player.speed       = 260.0;

    game.insect_count      = 0;
    game.level_index       = 0;
    game.score             = 0;
    game.lives             = 3;
    game.repairs           = 4;
    game.repair_timer      = 0.0;
    game.spawn_timer       = 0.0;
    game.elapsed           = 0.0;
    game.comparisons       = 0;
    game.naive_comparisons = 0;
    game.entry_name        = "";
    game.screen            = PLAYING;
}

/**
 * Move the spider with the arrow keys, keeping it inside the play area.
 * Takes the spider by reference so it is modified in place.
 */
static void move_spider(spider &player, double dt)
{
    double step = player.speed * dt;

    if (key_down(LEFT_KEY))  player.ent.pos.x -= step;
    if (key_down(RIGHT_KEY)) player.ent.pos.x += step;
    if (key_down(UP_KEY))    player.ent.pos.y -= step;
    if (key_down(DOWN_KEY))  player.ent.pos.y += step;

    double r = player.ent.radius;
    if (player.ent.pos.x < r)                    player.ent.pos.x = r;
    if (player.ent.pos.x > SCREEN_WIDTH - r)     player.ent.pos.x = SCREEN_WIDTH - r;
    if (player.ent.pos.y < 44 + r)               player.ent.pos.y = 44 + r;
    if (player.ent.pos.y > SCREEN_HEIGHT - r)    player.ent.pos.y = SCREEN_HEIGHT - r;
}

/**
 * Trickle repair charges back over time so a damaged web stays recoverable.
 */
static void recharge_repairs(game_data &game, double dt)
{
    if (game.repairs >= MAX_REPAIRS) return;

    game.repair_timer += dt;
    if (game.repair_timer >= REPAIR_RECHARGE)
    {
        game.repairs++;
        game.repair_timer = 0.0;
    }
}

/**
 * Insert a score into the ranked table, shifting lower entries down and
 * discarding the last when the table is full.
 */
static void record_score(game_data &game, const string &name, int value)
{
    int slot = game.score_count;
    for (int i = 0; i < game.score_count; i++)
    {
        if (value > game.scores[i].value)
        {
            slot = i;
            break;
        }
    }

    if (slot >= MAX_SCORES) return;

    int last = game.score_count;
    if (last >= MAX_SCORES) last = MAX_SCORES - 1;

    // Walk backwards so each entry is copied before it is overwritten.
    for (int i = last; i > slot; i--)
    {
        game.scores[i] = game.scores[i - 1];
    }

    game.scores[slot].name  = name;
    game.scores[slot].value = value;

    if (game.score_count < MAX_SCORES) game.score_count++;
}

/**
 * Advance one frame of play: input, spawning, movement, web load and
 * collision, then the level target check.
 */
static void update_playing(game_data &game, double dt)
{
    game.elapsed += dt;

    move_spider(game.player, dt);
    recharge_repairs(game, dt);

    if (key_typed(R_KEY)) repair_nearest(game);
    if (key_typed(D_KEY)) game.show_debug = not game.show_debug;
    if (key_typed(G_KEY)) game.show_grid  = not game.show_grid;
    if (key_typed(P_KEY)) { game.screen = PAUSED; return; }

    game.spawn_timer -= dt;
    if (game.spawn_timer <= 0.0)
    {
        spawn_insect(game);
        game.spawn_timer = game.levels[game.level_index].spawn_interval;
    }

    update_insects(game, dt);
    update_web(game, dt);
    broad_phase(game);

    if (game.screen != PLAYING) return;   // broad_phase may have ended the run

    if (game.score >= game.levels[game.level_index].target_score)
    {
        if (game.level_index < LEVEL_COUNT - 1)
        {
            game.level_index++;
            game.repairs += 2;
            game.screen   = LEVEL_COMPLETE;
        }
        else
        {
            game.screen = GAME_OVER;
        }
    }
}

/**
 * Collect up to three initials at game over, then file the score.
 */
static void update_game_over(game_data &game)
{
    for (int k = A_KEY; k <= Z_KEY; k++)
    {
        if (key_typed((key_code)k) and (int)game.entry_name.length() < NAME_LENGTH)
        {
            game.entry_name += (char)('A' + (k - A_KEY));
        }
    }

    if (key_typed(BACKSPACE_KEY) and game.entry_name.length() > 0)
    {
        game.entry_name = game.entry_name.substr(0, game.entry_name.length() - 1);
    }

    if (key_typed(RETURN_KEY))
    {
        string name = game.entry_name;
        if (name.length() == 0) name = "---";
        record_score(game, name, game.score);
        game.screen = SCORES;
    }
}

int main()
{
    open_window("Web Weaver", SCREEN_WIDTH, SCREEN_HEIGHT);

    game_data game;
    load_levels(game);
    game.score_count = 0;
    game.show_debug  = true;
    game.show_grid   = false;
    start_new_game(game);
    game.screen = MENU;

    create_timer("frame");
    start_timer("frame");
    unsigned int last_tick = timer_ticks("frame");

    while (not quit_requested())
    {
        process_events();

        // Seconds since the previous frame, clamped so a long stall cannot
        // teleport entities across the screen.
        unsigned int now = timer_ticks("frame");
        double dt = (now - last_tick) / 1000.0;
        last_tick = now;
        if (dt > 0.05) dt = 0.05;

        if (key_typed(ESCAPE_KEY)) break;

        // The screen state decides which update and draw pair runs.
        switch (game.screen)
        {
            case MENU:
                if (key_typed(RETURN_KEY)) start_new_game(game);
                if (key_typed(S_KEY))      game.screen = SCORES;
                draw_menu(game);
                break;

            case PLAYING:
                update_playing(game, dt);
                draw_playing(game);
                break;

            case PAUSED:
                if (key_typed(P_KEY)) game.screen = PLAYING;
                draw_paused(game);
                break;

            case LEVEL_COMPLETE:
                if (key_typed(RETURN_KEY)) game.screen = PLAYING;
                draw_level_complete(game);
                break;

            case GAME_OVER:
                update_game_over(game);
                draw_game_over(game);
                break;

            case SCORES:
                if (key_typed(RETURN_KEY)) game.screen = MENU;
                draw_scores(game);
                break;
        }

        refresh_screen(60);
    }

    close_all_windows();
    return 0;
}
